add hw file and update README.md
Davison322/Laba-5 pull request #1
Opened 2022-12-01 01:37 UTC by Davison322

Update Laba5

2022-12-21 16:32 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	public:
no need to specify the field type "public" again

2022-12-21 16:35 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	void listOfPlanetsAdd(Planet somePlanet)
The name of the function is capitalized (ListOfPlanetsAdd)

2022-12-21 16:50 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	vector<Planet> listOfPlanets;
change from "public" to "private"

2022-12-21 16:53 UTC, SolomiaSydoryk commented on Laba5.cpp
> +		int massInKg;
incorrect variable entry
should be written:
int mass_in_kg;

2022-12-21 16:56 UTC, SolomiaSydoryk commented on Laba5.cpp
> +		double lenghtOfDay;
incorrect variable entry
should be written:
int orbital_velocity;
double mean_temperature; or double value_of_temperature;
double lenght_of_day;

2022-12-21 16:57 UTC, SolomiaSydoryk commented on Laba5.cpp
> +		int distanceFromSun;
incorrect variable entry
should be written:
int distance_from_sun;

2022-12-21 17:04 UTC, SolomiaSydoryk commented on Laba5.cpp
> +		};
incorrect variable entry
should be written:
double lenght_of_day;

you can use "this->" for better recording
for example:
Planet(string name, int mass_in_kg, int orbital_velocity, double mean_temperature, double lenght_of_day, int distance_from_sun) {
this->name=name;
this->mass_in_kg=mass_in_kg; 
....
};

2022-12-21 17:04 UTC, SolomiaSydoryk commented on Laba5.cpp
> +		}
The name of the function is capitalized

2022-12-21 17:05 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	}
The name of the function is capitalized

2022-12-21 17:11 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	static double findAverageMass(vector<Planet> listOfPlanets)
static double FindAverageMass(vector<Planet> ListOfPlanets)

2022-12-24 10:55 UTC, SolomiaSydoryk commented on README.md
> +Додати функцію findAverageMass( Planet* )
Назви функцій з великої літери

2022-12-24 10:59 UTC, SolomiaSydoryk commented on Laba5.cpp
> +	vector<Planet> listOfPlanets;
or delete the next "public" (on line 40), you already have it, why again?

2023-01-27 18:44 UTC, SolomiaSydoryk commented on Laba5Header.h
> +enum type
Enumerators (for both scoped and unscoped enums) should be named like constants, not like macros. About all of them
For example

![Знімок екрана_20230127_203035](https://user-images.githubusercontent.com/119521489/215168977-45dee4b9-3d16-4ac2-80eb-2086951c099e.png)

2023-02-24 21:52 UTC, zveres-ss requested changes

2023-02-24 21:52 UTC, zveres-ss commented on Laba5.cpp
> +	Planet PlanetA("PlanetA", 1488, 77777, 14.5, 123456789, 500000);
variables should always start with lowerase

2023-02-24 21:52 UTC, zveres-ss commented on Laba5Header.h
> +	vector<Planet> listOfPlanets;
never use two different conventions in your code together:
int orbital_velocity; this is in previous class
vector<Planet> listOfPlanets; - here

either caselCase or snake_case

2023-03-18 23:35 UTC, closed without merging